package newpackage;

import java.math.BigInteger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author intel
 */
public class BigNumber_GUI_Frame extends javax.swing.JFrame {

    /**
     * Creates new form BigNumber_GUI_Frame
     */
    public BigNumber_GUI_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataTypeLabel = new javax.swing.JLabel();
        num1Label = new javax.swing.JLabel();
        num2Label = new javax.swing.JLabel();
        msgLabelMultiply = new javax.swing.JLabel();
        num1TextField = new javax.swing.JTextField();
        num2TextField = new javax.swing.JTextField();
        dataTypeMultiplyLabel = new javax.swing.JLabel();
        dataTypeMultiplyButton = new javax.swing.JButton();
        dataTypeMultiplyClearButton = new javax.swing.JButton();
        dataTypeFactorialLabel = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        numTextField = new javax.swing.JTextField();
        msgLabelFactorial = new javax.swing.JLabel();
        dataTypeFactorialButton = new javax.swing.JButton();
        dataTypeFactorialClearButton = new javax.swing.JButton();
        dataTypeSeparator = new javax.swing.JSeparator();
        bignumberLabel = new javax.swing.JLabel();
        bignumberMultiplyLabel = new javax.swing.JLabel();
        bignumberFactorialLabel = new javax.swing.JLabel();
        number1Label = new javax.swing.JLabel();
        number1TextField = new javax.swing.JTextField();
        number2Label = new javax.swing.JLabel();
        number2TextField = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        bugnumberMultiplyButton = new javax.swing.JButton();
        bignumberFactorialButton = new javax.swing.JButton();
        bignumberMultiplyClearButton = new javax.swing.JButton();
        bignumberFactorialClearButton = new javax.swing.JButton();
        bignumberSeparator = new javax.swing.JSeparator();
        resultLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BigNumber");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        dataTypeLabel.setText("                            Using Data Type");

        num1Label.setText("Num 1 =");

        num2Label.setText("Num 2 =");

        num2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2TextFieldActionPerformed(evt);
            }
        });

        dataTypeMultiplyLabel.setText("Multiply");

        dataTypeMultiplyButton.setText("Multiply");
        dataTypeMultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTypeMultiplyButtonActionPerformed(evt);
            }
        });

        dataTypeMultiplyClearButton.setText("Clear");
        dataTypeMultiplyClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTypeMultiplyClearButtonActionPerformed(evt);
            }
        });

        dataTypeFactorialLabel.setText("Factorial");

        numLabel.setText("Num = ");

        dataTypeFactorialButton.setText("Factorial");
        dataTypeFactorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTypeFactorialButtonActionPerformed(evt);
            }
        });

        dataTypeFactorialClearButton.setText("Clear");
        dataTypeFactorialClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTypeFactorialClearButtonActionPerformed(evt);
            }
        });

        bignumberLabel.setText("                     Using BigNumber");

        bignumberMultiplyLabel.setText("Multiply");

        bignumberFactorialLabel.setText("Factorial");

        number1Label.setText("Number 1 =");

        number2Label.setText("Number 2 =");

        numberLabel.setText("Number = ");

        bugnumberMultiplyButton.setText("Multiply");
        bugnumberMultiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugnumberMultiplyButtonActionPerformed(evt);
            }
        });

        bignumberFactorialButton.setText("Factorial");
        bignumberFactorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bignumberFactorialButtonActionPerformed(evt);
            }
        });

        bignumberMultiplyClearButton.setText("Clear");
        bignumberMultiplyClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bignumberMultiplyClearButtonActionPerformed(evt);
            }
        });

        bignumberFactorialClearButton.setText("Clear");
        bignumberFactorialClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bignumberFactorialClearButtonActionPerformed(evt);
            }
        });

        resultLabel.setText("            Result");

        textArea.setColumns(20);
        textArea.setRows(5);
        scrollPane.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(dataTypeMultiplyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(dataTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(dataTypeFactorialLabel)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(bignumberSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(bignumberMultiplyLabel)
                        .addGap(430, 430, 430)
                        .addComponent(bignumberFactorialLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(numberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 30, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(bugnumberMultiplyButton)
                        .addGap(18, 18, 18)
                        .addComponent(bignumberMultiplyClearButton)
                        .addGap(319, 319, 319)
                        .addComponent(bignumberFactorialButton)
                        .addGap(26, 26, 26)
                        .addComponent(bignumberFactorialClearButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(num1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(num1TextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(num2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(dataTypeMultiplyButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(dataTypeMultiplyClearButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(msgLabelMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(num2TextField))))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataTypeFactorialButton)
                                .addGap(27, 27, 27)
                                .addComponent(dataTypeFactorialClearButton)
                                .addGap(18, 18, 18)
                                .addComponent(msgLabelFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(number2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(bignumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(dataTypeSeparator)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataTypeMultiplyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataTypeFactorialLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num1Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dataTypeMultiplyButton)
                                .addComponent(dataTypeMultiplyClearButton))
                            .addComponent(msgLabelMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgLabelFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dataTypeFactorialButton)
                                .addComponent(dataTypeFactorialClearButton)))))
                .addGap(22, 22, 22)
                .addComponent(dataTypeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(bignumberLabel)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bignumberMultiplyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(bignumberFactorialLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(number1Label)
                            .addComponent(number1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberLabel)
                            .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number2Label)
                    .addComponent(number2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bugnumberMultiplyButton)
                    .addComponent(bignumberFactorialButton)
                    .addComponent(bignumberMultiplyClearButton)
                    .addComponent(bignumberFactorialClearButton))
                .addGap(20, 20, 20)
                .addComponent(bignumberSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        setSize(new java.awt.Dimension(891, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void num2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2TextFieldActionPerformed

    private void dataTypeMultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTypeMultiplyButtonActionPerformed
        // TODO add your handling code here:
        String s1 = num1TextField.getText();
        String s2 = num2TextField.getText();
        try{long s3 = Long.parseLong(s1);
        long s4 = Long.parseLong(s2);
        long s = s3 * s4;
        String s5 = "" + s;
        textArea.setText(s5);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "number out of bounds");
        }
        //long s6 = -9223372036854775808l;
        //long s7 = 9223372036854775807l;
        //String s8 = "" + s6;
        //String s9 = "" + s7;
        //if((s3>s6||s3<s7)&&(s4>s6||s4<s7))
        //if((s1.equals(s8) || s1.equals(s9)) && (s2.equals(s8) || s2.equals(s9)))
        // {
        
        //} else {
        //String msg = "Invalid Input";
        //msgLabelMultiply.setText(msg);
        //}

    }//GEN-LAST:event_dataTypeMultiplyButtonActionPerformed

    private void dataTypeMultiplyClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTypeMultiplyClearButtonActionPerformed
        // TODO add your handling code here:
        num1TextField.setText(null);
        num2TextField.setText(null);
        textArea.setText(null);
        msgLabelMultiply.setText(null);
    }//GEN-LAST:event_dataTypeMultiplyClearButtonActionPerformed

    private void dataTypeFactorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTypeFactorialButtonActionPerformed
        // TODO add your handling code here:
        String f = numTextField.getText();
        long fact = Long.parseLong(f);
        long fac = 1;
        for (int i = 1; i <= fact; i++) {
            fac = fac * i;
        }
        String factorial = "" + fac;
        textArea.setText(factorial);

    }//GEN-LAST:event_dataTypeFactorialButtonActionPerformed

    private void dataTypeFactorialClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTypeFactorialClearButtonActionPerformed
        // TODO add your handling code here:
        numTextField.setText(null);
        textArea.setText(null);
    }//GEN-LAST:event_dataTypeFactorialClearButtonActionPerformed

    private void bugnumberMultiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugnumberMultiplyButtonActionPerformed
        // TODO add your handling code here:
        String s1=number1TextField.getText();
        String s2=number2TextField.getText();
        BigInteger num1=new BigInteger(s1);
        BigInteger num2=new BigInteger(s2);
        BigInteger Multiplication;
        Multiplication=num1.multiply(num2);
        String s3=Multiplication.toString();
        textArea.setText(s3);
    }//GEN-LAST:event_bugnumberMultiplyButtonActionPerformed

    private void bignumberMultiplyClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bignumberMultiplyClearButtonActionPerformed
        // TODO add your handling code here:
        number1TextField.setText(null);
        number2TextField.setText(null);
        textArea.setText(null);
    }//GEN-LAST:event_bignumberMultiplyClearButtonActionPerformed

    private void bignumberFactorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bignumberFactorialButtonActionPerformed
        // TODO add your handling code here:
        String s=numberTextField.getText();
        long n=Long.parseLong(s);
        BigInteger fact=new BigInteger("1");
        for (long i = 1; i <=n; i++)
        {
            fact=fact.multiply(BigInteger.valueOf(i));
        }
        String s1=fact.toString();
        
        boolean stat = false;
        String ans="";
        for(int i=0;i<s1.length();i++)
        {
            ans+=s1.charAt(i);
            if(i%180==0 && stat)
                ans+='\n';
            stat=true;
        }
        textArea.setText(ans);
    }//GEN-LAST:event_bignumberFactorialButtonActionPerformed

    private void bignumberFactorialClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bignumberFactorialClearButtonActionPerformed
        // TODO add your handling code here:
        numberTextField.setText(null);
        textArea.setText(null);
    }//GEN-LAST:event_bignumberFactorialClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BigNumber_GUI_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BigNumber_GUI_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BigNumber_GUI_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BigNumber_GUI_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BigNumber_GUI_Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bignumberFactorialButton;
    private javax.swing.JButton bignumberFactorialClearButton;
    private javax.swing.JLabel bignumberFactorialLabel;
    private javax.swing.JLabel bignumberLabel;
    private javax.swing.JButton bignumberMultiplyClearButton;
    private javax.swing.JLabel bignumberMultiplyLabel;
    private javax.swing.JSeparator bignumberSeparator;
    private javax.swing.JButton bugnumberMultiplyButton;
    private javax.swing.JButton dataTypeFactorialButton;
    private javax.swing.JButton dataTypeFactorialClearButton;
    private javax.swing.JLabel dataTypeFactorialLabel;
    private javax.swing.JLabel dataTypeLabel;
    private javax.swing.JButton dataTypeMultiplyButton;
    private javax.swing.JButton dataTypeMultiplyClearButton;
    private javax.swing.JLabel dataTypeMultiplyLabel;
    private javax.swing.JSeparator dataTypeSeparator;
    private javax.swing.JLabel msgLabelFactorial;
    private javax.swing.JLabel msgLabelMultiply;
    private javax.swing.JLabel num1Label;
    private javax.swing.JTextField num1TextField;
    private javax.swing.JLabel num2Label;
    private javax.swing.JTextField num2TextField;
    private javax.swing.JLabel numLabel;
    private javax.swing.JTextField numTextField;
    private javax.swing.JLabel number1Label;
    private javax.swing.JTextField number1TextField;
    private javax.swing.JLabel number2Label;
    private javax.swing.JTextField number2TextField;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
